DESCRIPTIONS = {
  'ADJ': ('adjective', 'new, good, high, special, big, local'),
  'ADV': ('adverb', 'really, already, still, early, now'),
  'CC': ('Coordinating conjunction', ''),
  'CD': ('Cardinal number', ''),
  'CNJ': ('conjunction', 'and, or, but, if, while, although'),
  'DET': ('determiner', 'the, a, some, most, every, no'),
  'DT': ('Determiner', ''),
  'EX':  ('existential there', 'there\'s'),
  'FW':  ('foreign word', 'dolce, ersatz, esprit, quo, maitre'),
  'IN': ('Preposition or subordinating conjunction', ''),
  'JJ': ('Adjective', ''),
  'JJR': ('Adjective, comparative', ''),
  'JJS': ('Adjective, superlative', ''),
  'LS': ('List item marker', ''),
  'MD': ('Modal', ''),
  'MOD': ('modal verb', 'will, can, would, may, must, should'),
  'N':   ('noun', 'year, home, costs, time, education'),
  'NN': ('Noun, singular or mass', ''),
  'NNP': ('Proper noun, singular', ''),
  'NNPS': ('Proper noun, plural', ''),
  'NNS': ('Noun, plural', ''),
  'NP':  ('proper noun', 'Alison, Africa, April, Washington'),
  'NUM': ('number', 'twenty-four, fourth, 1991, 14:24'),
  'P':   ('preposition', 'on, of, at, with, by, into, under'),
  'PDT': ('Predeterminer', ''),
  'POS': ('Possessive ending', ''),
  'PRO': ('pronoun', 'he, their, her, its, my, I, us'),
  'PRP$': ('Possessive pronoun (prolog version PRP-S)', ''),
  'PRP': ('Personal pronoun', ''),
  'RB': ('Adverb', ''),
  'RBR': ('Adverb, comparative', ''),
  'RBS': ('Adverb, superlative', ''),
  'RP': ('Particle', ''),
  'SYM': ('Symbol', ''),
  'TO':  ('the word to', 'to'),
  'UH':  ('interjection', 'ah, bang, ha, whee, hmpf, oops'),
  'V':   ('verb', 'is, has, get, do, make, see, run'),
  'VB': ('Verb, base form', ''),
  'VBD': ('Verb, past tense', ''),
  'VBG': ('Verb, gerund or present participle', ''),
  'VBN': ('Verb, past participle', ''),
  'VBP': ('Verb, non-3rd person singular present', ''),
  'VBZ': ('Verb, 3rd person singular present', ''),
  'VD':  ('past tense', 'said, took, told, made, asked'),
  'VG':  ('present participle', 'making, going, playing, working'),
  'VN':  ('past participle', 'given, taken, begun, sung'),
  'WDT': ('Wh-determiner', ''),
  'WH':  ('wh determiner', 'who, which, when, what, where, how'),
  'WP$': ('Possessive wh-pronoun (prolog version WP-S)', ''),
  'WP': ('Wh-pronoun', ''),
  'WRB': ('Wh-adverb', '')
}
